project:
  type: website
  output-dir: docs

website:
  title: "EST603 Energy Systems Analysis"
  navbar:
    background: light
    right:
      - text: Home
        href: index.qmd
      - text: Syllabus
        href: syllabus.qmd
      - text: Schedule
        href: schedule.qmd        
      - text: Lectures
        menu:
          - text: All Lectures
            href: lectures.qmd
          - text: Lecture 1
            href: lectures/lecture1/index.qmd
          - text: Lecture 2
            href: lectures/lecture2/index.qmd
          - text: Lecture 3
            href: lectures/lecture3/index.qmd 
          - text: Lecture 4
            href: lectures/lecture4/index.qmd
          - text: Lecture 5
            href: lectures/lecture5/index.qmd
          - text: Lecture 6
            href: lectures/lecture6/index.qmd                                                
      - text: Homework
        menu:
          - text: HW 0
            href: homeworks/hw0.qmd
          - text: HW 1
            href: homeworks/hw1.qmd
          - text: HW 2
            href: homeworks/hw2.qmd
      - text: Resources
        href: resources.qmd
  page-navigation: true
  page-footer: 
    left: "Copyright &copy; 2022 [Gang He](http://drganghe.github.io). All rights reserved." 
    right: 
      - icon: github
        href: https://github.com/drganghe/est603-energy-systems-analysis-2022-fall
      - icon: twitter 
        href: https://twitter.com/DrGangHe
  search:
    location: navbar
    type: textbox
  reader-mode: true
  repo-url: https://github.com/drganghe/est603-energy-systems-analysis-2022-fall
  repo-actions: [edit, issue, source]
  twitter-card: true
  #  creator: "@DrGangHe"
  #  image: "/lectures/lecture2/images/boe-equations.png"
  site-url: "https://drganghe.github.io/est603-energy-systems-analysis-2022-fall"


bibliography: readings.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true
    #link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'

comments:
  hypothesis: false
  

